<a href="https://colab.research.google.com/github/kapilkn/ML/blob/master/ML_Ensemble_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ensemble Learning and Cross Validation
Key Terms: XGBoost, AdaBoost, KFold, 

**Kapil Nagwanshi**

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = (18,10)
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

In [4]:
cd gdrive

/content/gdrive


In [5]:
cd 'My Drive'

/content/gdrive/My Drive


In [6]:
cd 'Colab Notebooks'

/content/gdrive/My Drive/Colab Notebooks


In [7]:
df = pd.read_csv('pima-indians-diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [0]:
array = df.values

In [0]:
X = array[:,0:8]
Y = array[:,8]
seed =7 
num_trees = 30

In [11]:
kfold = model_selection.KFold(n_splits=10,random_state=seed)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


In [0]:
model = AdaBoostClassifier(n_estimators=num_trees,random_state=seed)

In [0]:
results = model_selection.cross_val_score(model,X,Y,cv=kfold)

In [14]:
print(results)

[0.67532468 0.80519481 0.7012987  0.68831169 0.75324675 0.80519481
 0.79220779 0.83116883 0.73684211 0.81578947]


In [15]:
print(results.mean())

0.760457963089542


In [16]:
from sklearn import svm
from xgboost import XGBClassifier
clf = XGBClassifier()

seed =7 
num_trees = 30
kfold = model_selection.KFold(n_splits=10,random_state=seed)
model = XGBClassifier(n_estimators=num_trees,random_state=seed)
results = model_selection.cross_val_score(model,X,Y,cv=kfold)
print(results)
print('---------------------')
print(results.mean())

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


[0.7012987  0.85714286 0.71428571 0.63636364 0.76623377 0.80519481
 0.83116883 0.84415584 0.72368421 0.80263158]
---------------------
0.768215994531784


## Cross Validation

In [0]:
from sklearn.datasets import load_iris

In [0]:
iris_data = load_iris()

In [19]:
print(iris_data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [0]:
data_input = iris_data.data
data_output = iris_data.target

In [23]:
print(data_input)
print('-------------------------------')
print(data_output)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [0]:
from sklearn.model_selection import KFold
kf = KFold (n_splits =5, shuffle = True)

In [25]:
print('Train Set        Test Set      ')
for train_set, test_set in kf.split(data_input):
  print(train_set,test_set)

Train Set        Test Set      
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  21  22  23  24  26  27  28  29  30  32  34  35  36  37  38  39  40
  41  42  43  44  45  46  48  49  50  52  54  55  56  58  59  60  61  63
  65  66  67  68  69  71  72  73  75  77  78  79  82  84  85  87  88  89
  90  92  93  96  97  99 100 101 102 104 106 107 108 109 110 112 114 115
 116 117 118 119 120 123 124 125 126 127 128 129 131 132 133 134 135 136
 137 138 139 140 141 142 144 145 146 147 148 149] [  0  20  25  31  33  47  51  53  57  62  64  70  74  76  80  81  83  86
  91  94  95  98 103 105 111 113 121 122 130 143]
[  0   1   2   3   4   5   6   7   9  10  11  12  14  16  17  18  19  20
  21  22  23  24  25  26  28  30  31  33  34  35  39  41  42  43  44  45
  46  47  48  49  51  52  53  54  56  57  58  60  62  63  64  67  68  69
  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
  88  89  91  93  94  95  96  97  98 101 103 104 105 106 108 109 

In [0]:
from sklearn.ensemble import RandomForestClassifier
rf_class = RandomForestClassifier(n_estimators=10)

In [0]:
from sklearn.model_selection import cross_val_score

In [28]:
print(cross_val_score(rf_class,data_input, data_output, scoring='accuracy',cv=10))

[1.         0.93333333 1.         0.93333333 0.93333333 0.86666667
 0.93333333 1.         1.         1.        ]


In [30]:
accuracy = cross_val_score(rf_class,data_input, data_output, scoring='accuracy',cv=10).mean()*100
print('Accuracy of Random Forest is: ', accuracy, '%')

Accuracy of Random Forest is:  96.0 %
